<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRunner" project="09March2024BDDCucumberProject" tests="3" started="3" failures="3" errors="0" ignored="0">
  <testsuite name="runner.TestRunner" time="54.056">
    <testsuite name="Customer" time="54.056">
      <testcase name="Add New Customer #1" classname="Customer" time="20.785">
        <failure>java.lang.AssertionError: expected [× The new customer has been added successfully.] but found [×
The new customer has been added successfully.]&#13;
	at org.testng.Assert.fail(Assert.java:96)&#13;
	at org.testng.Assert.failNotEquals(Assert.java:776)&#13;
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)&#13;
	at org.testng.Assert.assertEquals(Assert.java:118)&#13;
	at org.testng.Assert.assertEquals(Assert.java:453)&#13;
	at org.testng.Assert.assertEquals(Assert.java:463)&#13;
	at stepDefinations.StepDefination.user_can_view_confirmation_msg(StepDefination.java:138)&#13;
	at ✽.User can view confirmation msg "× The new customer has been added successfully."(file:///C:/Users/043479744/eclipse-workspace/09March2024BDDCucumberProject/./Features/AddNewCust.feature:15)&#13;
&#13;
</failure>
      </testcase>
      <testcase name="Add New Customer #2" classname="Customer" time="16.656">
        <failure>java.lang.AssertionError: expected [× The new customer has been added successfully.] but found [×
The new customer has been added successfully.]&#13;
	at org.testng.Assert.fail(Assert.java:96)&#13;
	at org.testng.Assert.failNotEquals(Assert.java:776)&#13;
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)&#13;
	at org.testng.Assert.assertEquals(Assert.java:118)&#13;
	at org.testng.Assert.assertEquals(Assert.java:453)&#13;
	at org.testng.Assert.assertEquals(Assert.java:463)&#13;
	at stepDefinations.StepDefination.user_can_view_confirmation_msg(StepDefination.java:138)&#13;
	at ✽.User can view confirmation msg "× The new customer has been added successfully."(file:///C:/Users/043479744/eclipse-workspace/09March2024BDDCucumberProject/./Features/AddNewCust.feature:15)&#13;
&#13;
</failure>
      </testcase>
      <testcase name="Add New Customer #3" classname="Customer" time="16.612">
        <failure>java.lang.AssertionError: expected [× The new customer has been added successfully.] but found [×
The new customer has been added successfully.]&#13;
	at org.testng.Assert.fail(Assert.java:96)&#13;
	at org.testng.Assert.failNotEquals(Assert.java:776)&#13;
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)&#13;
	at org.testng.Assert.assertEquals(Assert.java:118)&#13;
	at org.testng.Assert.assertEquals(Assert.java:453)&#13;
	at org.testng.Assert.assertEquals(Assert.java:463)&#13;
	at stepDefinations.StepDefination.user_can_view_confirmation_msg(StepDefination.java:138)&#13;
	at ✽.User can view confirmation msg "× The new customer has been added successfully."(file:///C:/Users/043479744/eclipse-workspace/09March2024BDDCucumberProject/./Features/AddNewCust.feature:15)&#13;
&#13;
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
